# Generated by Django 4.0.6 on 2022-07-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_tracklist_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracklist',
            name='single',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
