# Generated by Django 4.0.6 on 2022-07-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_tracklist_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tracklist',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='album',
            name='band_members',
            field=models.ManyToManyField(to='main_app.bandmembers'),
        ),
    ]
