# Generated by Django 4.0.6 on 2022-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_bandmembers_bandmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='instrument',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bandmember',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
